version: '3'
services:
  app:
    image: golang:1.21rc2-alpine3.18
    working_dir: /app
    environment:
      EXP_CONFIG_DATABASE_NAME: expense_dev
      EXP_CONFIG_USER_NAME: root
      EXP_CONFIG_PASS_NAME: root
      EXP_CONFIG_HOST_NAME: mysqldb
      EXP_CONFIG_PORT_NUMB: 3306
    volumes:
      - $PWD:/app
    command: tail -f /dev/null
    ports:
      - 9001:9001
    networks:
      - docker-compose-files_mysql

networks:
  docker-compose-files_mysql:
    external: true