#docker-compose -f docker-compose.yml up -d
version: '3.7'

services:
  mysqldb:
    image: mysql:8.0.29-oracle
    container_name: mysql
    restart: always #restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expense
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - mysql-database

  mysqladmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: mysqladmin
    depends_on:
      - mysqldb
    links:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8000:80
    networks:
      - mysql-database

  expense:
    depends_on:
      - mysqldb
    image: uzrnem/expense:0.2.6
    container_name: expense
    environment:
      EXP_CONFIG_DATABASE_NAME: expense
      EXP_CONFIG_USER_NAME: root
      EXP_CONFIG_PASS_NAME: root
      EXP_CONFIG_HOST_NAME: mysqldb
      EXP_CONFIG_PORT_NUMB: 3306
    ports:
      - 9001:9001
    networks:
      - mysql-database

  phinx:
    image: uzrnem/phinx:0.4 # uzrnem/phinx:0.4-mac
    container_name: phinx
    volumes:
      - $PWD/schema:/phinx/db
    depends_on:
      - mysqldb
    environment:
      PHINX_DB_HOST: mysqlhost
      PHINX_DB_DATABASE: expense
      PHINX_DB_USERNAME: root
      PHINX_DB_PASSWORD: root
    command:  ./vendor/bin/phinx migrate && ./vendor/bin/phinx seed:run -s AccountTypeSeeder -s TransactionTypeSeeder -s TagSeeder
    networks:
      - mysql-database

networks:
  mysql-database:
    driver: bridge