version: '3.7'

services:
  go-expense:
    depends_on:
      - mysqldb
    image: uzrnem/expense:0.2.4
    container_name: goexpense
    environment:
      EXP_CONFIG_DATABASE_NAME: expense_dev
      EXP_CONFIG_USER_NAME: root
      EXP_CONFIG_PASS_NAME: root
      EXP_CONFIG_HOST_NAME: mysqldb
      EXP_CONFIG_PORT_NUMB: 3306
    ports:
      - 9001:9001
    networks:
      - docker-compose-files_mysql

networks:
  docker-compose-files_mysql:
    external: true
